### ISSUE TITLE
Behavior of Oxygen-Oxygen case not consistent with Java sim

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#8] opened 2015-02-26 02:14 UTC
When the oxygen atom is moved in the Oxygen-Oxygen case, the behavior doesn't match the Java sim.

(1) When the moving atom is moved a very small distance, a "bond" vibration does correctly occur. BUT, the pinned (left) atom should only vibrate momentarily, and then it should stop. Only the moving (right) atom continues to vibrate back and forth.

(2) When the moving atom is moved even halfway up right side of the vertical part of the curve from a stationary position, often the atom escapes off-screen. Sometimes the return atom button appears AND THEN the atom returns in an instant and is "bonded" resulting in the expected vibrations. The distance moved to cause an escaped atom does not seem consistent, either.

(3) When bonded (and the moving atom is vibrating), the point on the graph fluctuates and jumps around much more than it did in the Java sim.

**Comment by notsiddhartha** [comment] 2015-02-26 05:12
The epsilon value for Oxygen-Oxygen is different from the java sim. 

From the spec:
**1. Change value of variable EPSILON when Oxygen Oxygen option is selected**
_Previous value: EPSILON = 423.3
New value: EPSILON = 59500_

Could this be a valid reason for the above behaviour?

**Comment by ycarpenterphet** [comment] 2015-02-26 05:22
Although I don't think this change in the epsilon value should have affected the behaviour in the bonding case, I can't be certain.

@jbphet, can you comment on this case where both atoms are oxygen and see if the change in epsilon would cause the behavior changes described? All I have written in my notes is that the sim runs different code to determine the behaviour when both atoms are oxygen.

**Comment by jbphet** [comment] 2015-03-06 20:16
I haven't examined the ported code in detail, but it seems to me the epsilon value isn't enough to explain the discrepancies in the behavior between the HTML5 sim and the Java sim.  Oxygen bonding is handled as a special case in the code, and it looks like something didn't quite get translated correctly in the HTML5 version.  It may be that the special case expected a certain epsilon value and now needs some compensation, but this is only speculation.

Assigning to @notsiddhartha to work on making the HTML5 version behave like the Java version.  @notsiddhartha - If you find that there is some fundamental reason that this is impossible or very difficult due to the change in epsilon value, please let me know and I'll get more involved.

**Comment by ycarpenterphet** [comment] 2015-05-08 19:26
@notsiddhartha Just checking in with this issue, especially parts (1) and (2) reported initially. 

Can you comment on how things are progressing?

**Comment by notsiddhartha** [comment] 2015-05-11 14:24
(1) The left atom stops vibrating after a while, but it currently takes longer than the corresponding Java version. Investigating the cause for this.
(2) Cannot reproduce any more.

**Comment by ChandrashekarBemagoni** [comment] 2015-05-12 13:30
Fixed in above commit. Assigning  to @ycarpenterphet for verification

**Comment by jbphet** [comment] 2015-05-18 15:25
Assigning to @phet-steele to test, he can close if behaviors compare well.

**Comment by phet-steele** [comment] 2015-05-18 17:07
Looking at (1), this was hard to check. The occasional times when bonding occurred, the pinned atom does stop vibrating but takes about twice the time to stop when compared to java (and also has much more violent vibrations). The reason why (1) was hard to check was because at nearly any distance I dragged the right molecule out, the atom escaped instead of bonding.

(3) is consistent with java.

**Comment by notsiddhartha** [comment] 2015-05-19 18:06
@phet-steele, I have timed the bonding vibration duration of Java and HTML versions using a stopwatch and they seem to be in the 1-2 second range for both. Though this method is not very accurate, I didn't observe the HTML version taking twice as longer (Win 7, Chrome, Firefox). 
Could you let us know on which OS and browser combination this was observed?

**Comment by phet-steele** [comment] 2015-05-20 15:39
Well yesterday and today the time between the Java and HTML version was similar, so I'm going to say it's no longer an issue. The two problems I'm having are inconsistent distances that cause the atom to escape instead of bond, and the occasional time when the one atom moves to the right first then back to the left and bonds. Neither of these are seen in Java. I'm using Win 8.1 (IE11, FF 38, Chrome 42). Here's a video in Chrome, where the first two drags are to show the inconsistent escape distance, and the third drag shows the dragged atom jumping to the right first then bonding:

https://drive.google.com/file/d/0B3HJopSo_QqLa3F4ZzBnd1hDSzQ/view?usp=sharing

**Comment by ycarpenterphet** [comment] 2015-07-10 20:34
Now, the pinned atom vibration looks larger and more stilted than in the Java. Also, the continued vibrations of the unpinned atom are so small that they basically can't be seen. This is a big problem, since students need to be able to see this vibration.

(cc @arouinfar)

**Comment by phet-steele** [comment] 2016-07-05 20:12
@arouinfar this issue is the bane of my existence, so I'll pass it off to you with this question:
Above, Yuen-ying stated

> the continued vibrations of the unpinned atom are so small that they basically can't be seen. This is a big problem, since students need to be able to see this vibration.

I feel it is the case in 1.0.0-dev.7 that the vibrations are indeed obvious to the student, however, said vibrations in HTML5 and _insanely_ faster than Java. Thoughts on whether that's a problem? Is one of the versions more accurate than the other?

**Comment by arouinfar** [comment] 2016-07-07 17:41
@phet-steele I consulted with @amyh-phet, since this is more in her wheelhouse. 

In general, the speed of the vibration is not important, so long as the vibration can be seen. HOWEVER, the vibration looks far less obvious in  dev.10 than in the Java version. When the unpinned atom is vibrating alone, it looks more like it has a shadow behind it than it is in motion.

Currently, the layering of the atoms doesn't match the Java version. Perhaps this contributes to the problem.

@jbphet can you swap the layering of the atoms, so that the unpinned atom is behind the pinned atom?

**Comment by jbphet** [comment] 2016-08-01 23:02
This should now be fixed, assigning to @phet-steele to verify on master.

**Comment by jbphet** [comment] 2016-08-01 23:03
I forgot that this repo is separate from the one where most of its code resides, so the commit was not properly referenced.  The fix was committed here: https://github.com/phetsims/states-of-matter/commit/717c75759bc98c8c89e83ecab116fccc8de08605

**Comment by phet-steele** [comment] 2016-08-02 15:21
Points in the first comment look addressed, anything remaining is handled in other issues, like #54

**Closed as completed by phet-steele** 2016-08-02 15:21 UTC
Labels: type:bug
