### ISSUE TITLE
Optimize horizontal scaling of graph (and atoms!)

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#31] opened 2015-03-03 02:05 UTC
Reducing the atom diameter due to the decreased vertical spacing in the sim, and to avoid overlap with the graph has resulted in changed horizontal scaling of the graph (since the graph is intended to align with the atoms, sigma scales according to atom diameter (except oxygen), and sigma determines the left edge placement of the curve on the plot).

The consequence is that we now have a graph that 
(i) doesn't display the shape of the curve as well as the Java version [which is important for student learning], and 
(ii) leaves a much longer "tail" of the curve at the right (where the force on the atom is very small, leading to the misperception that the atom is not moving at all nor attracted to the other atom).

We'll need to iterate a bit to find optimal size parameters, possibly allow for the atoms to overlap (or change the range of sigma values available), or otherwise tweak the sim to correct these issues.

Note also that the much deeper well for oxygen also creates some labelling issues, where the vertical arrow indicating epsilon is very close to the left-side of the curve (such that it is difficult to see) - hopefully the horizontal scaling changes will also ameliorate this problem (if not, we'll create a new issue for that, and possibly fudge the epsilon value to be much larger but not "realistically" large).

**Comment by ycarpenterphet** [comment] 2015-03-03 02:07
@arouinfar You and I should tackle this, with some help in implementation from @jbphet, and possibly input from the rest of the team once we narrow down what our best case scenarios are. We'll want to wait until the sim matches the existing spec first, though, since the graph sizing and alignment is currently being tweaked already.

**Comment by arouinfar** [comment] 2016-08-03 17:50
@jbphet I'd like to talk this over with a chemist -- probably @amyh-phet to see what needs to be prioritized here.

**Comment by arouinfar** [comment] 2016-08-04 20:37
Spoke with @amyh-phet about this issue and we've decided try the following:
- Chop off 2/3 of the last column to reduce the tail
- Rescale the graph to fill in <i>some</i> of the lost space (requires rescaling the atom size)
- Reduce maximum atomic diameter allowed for adjustable attraction by ~20% to make up for lost vertical space

I will play with the mockups to see how this will look.

**Comment by arouinfar** [comment] 2016-08-08 22:25
@amyh-phet and I have discussed this issue a bit more, and given the rather significant changes that would be required to re-scale the graph, we've decided to put this on hold until after the sim is interviewed on. 

I'll be scheduling interviews for later this week. If I observe any significant student difficulties related to this issue, we can reconsider what changes will be necessary.

If the interviews go well, we can leave the graph as-is, and make a note about the scaling in the Teacher Tips.

**Comment by arouinfar** [comment] 2016-08-12 19:15
I conducted two interviews on this sim this week. Students often move the unpinned atom towards the pinned one, let go, watch it repel, catch it on the tail of the potential, and then move it towards the pinned atom again. 

A few times, students dragged the upinned atom out along the tail, let go for about a second, and then dragged the unpinned atom back towards the pinned one. It wasn't clear if they thought the atom was stuck or in a stable position out on the tail, or if they were just impatient.

Perhaps if we had a Fast Forward option, it would be more obvious that the atom is still moving (albeit, slowly) when it is far out on the tail. Fast Forward could be whatever speed necessary for neon-neon to be visibly moving when dragged all the way out on the tail.

We would need to do a little bit of rearranging to add a Fast Forward option below Normal. The graph and atoms could be pushed a bit higher until the graph and selection panel are top aligned. Slow Motion and Normal could be shifted up slightly, and then Fast Forward could be added below Normal. 

![image](https://cloud.githubusercontent.com/assets/8419308/17634053/e356179c-608d-11e6-8454-fa34b3e3b88a.png)

I'm not entirely sure how feasible this would be, but it seems far less invasive than resizing/rescaling the graph and and atoms. @jbphet can you give an estimate of how difficult it would be to add a Fast Forward option?

**Comment by jbphet** [comment] 2016-08-22 21:55
I figured it would probably be faster to implement the fast-forward feature and have us review it than to provide an estimate and discuss, so the the feature is now available on master.  @arouinfar and @ariel-phet - please take a look and see if you think this change addresses the issue with the long tail and we can decide whether to keep it.

I had a couple of observations:
- I had to go with a very high value for the fast forward - about 12.5 x normal speed - before the movement at the tail for neon-neon was anything that I though people would notice within 1 second.  This causes aliasing on slower devices, such as an iPad 2.  It worked fine on the iPad Air 2 that I tested (Dalton).
- I'm a bit skeptical that this will solve the problem.  Users would have to either set fast-forward and then move the atom, or vice versa, and I suspect that they will just move it out to the end while the speed is set to "Normal", drop it, notice that nothing much happens, and move it back.  From a learning standpoint, that doesn't seem like a bad thing to me.
- I tried dragging the neon atom to the end of the tail on the Java sim, and it doesn't move much there either, so it doesn't seem to me like this is a new issue being introduced by the port to HTML5.

**Comment by ariel-phet** [comment] 2016-08-25 00:01
I think the sim just needs some relayout and scaling. I believe below shows ipad dimensions (I have chopped off the right edge of the graph, did veritical adjustment of layout, and rescaled graph to fill the space)

![atomic](https://cloud.githubusercontent.com/assets/4051174/17952106/c9f56b22-6a24-11e6-9f75-97258e0e0179.PNG)

**Comment by ariel-phet** [comment] 2016-08-25 00:03
I believe what I have above matches the java scaling more closely

**Comment by arouinfar** [comment] 2016-08-25 02:39
@jbphet and I spoke about this before I left the office, and he showed me the aliasing issue on the iPad2. The motion of the unpinned atom can look very jerky, and I think it could lead to a more problematic student interpretation than the atom appearing static along the tail, so I don't think we want the Fast Forward option, after all.

@amyh-phet and I had discussed a re-scaling similar to what @ariel-phet mocked up. The problem is that the sigma in the graph is tied to the atomic diameter, so rescaling the graph requires rescaling the atoms too. We would probably need to remove the upper ~20% from the custom attraction's radius to handle the rescaling.

**Comment by jbphet** [comment] 2016-08-25 17:47
@ariel-phet and I just discussed this, and we're thinking of just shortening the graph.  It's pretty short on the Java sim, so how about we just do that?

**Comment by arouinfar** [comment] 2016-08-25 17:48
@jbphet @ariel-phet I would be fine with that. I think we could lose ~1/2-2/3 of the right-most column.

**Comment by ariel-phet** [comment] 2016-08-26 16:10
@jbphet perhaps when you do that, move the graph a bit to the right to recenter it in the negative space, and also move the atoms over to compensate accordingly

**Comment by arouinfar** [comment] 2016-08-31 16:52
> move the graph a bit to the right to recenter it in the negative space, and also move the atoms over to compensate accordingly

👍

**Comment by arouinfar** [comment] 2016-08-31 16:53
I have one additional request, though perhaps it goes without saying. After rescaling, the vertical lines should be re-distributed so that there are three columns of equal width.

**Comment by jbphet** [comment] 2016-08-31 18:28
I forgot that this GitHub issue was in the atomic interactions repo and didn't specify the full URL when making one of the main commits, so here it is: https://github.com/phetsims/states-of-matter/commit/c949c182c680d955111dbb6e0129fc377814226c.

**Comment by arouinfar** [comment] 2016-08-31 19:36
I just took a look at dev.12, and I think it looks great @jbphet!

**Comment by jbphet** [comment] 2016-08-31 19:46
Wow @arouinfar, I was just about to ask you to take a look at it.  Good anticipation.  Assigning to @ariel-phet to see if he concurs and, if so, I'll set up a dev task for this version.

**Comment by arouinfar** [comment] 2016-08-31 19:49
Haha @jbphet. I tried to pull master, but phettest wasn't behaving (might be a VPN issue on my end) so I took a look to see if there as a new dev version, and there was!

**Comment by ariel-phet** [comment] 2016-09-01 17:16
All looks good to me. Closing

**Closed as completed by ariel-phet** 2016-09-01 17:16 UTC
Labels: type:question, design:general
